from datetime import datetime

from jsonype import FromJsonConverter, ToJsonConverter
from jsonype.basic_from_json_converters import FunctionBasedFromSimpleJsonConverter
from jsonype.basic_to_json_converters import FunctionBasedToSimpleJsonConverter


# mimic class name
# noinspection PyPep8Naming
def ToDatetime() -> FromJsonConverter[datetime, None]:  # noqa: N802
    """Return a converter that converts a JSON string to a :class:`datetime.datetime`.

    The JSON string is expected to be in ISO-format (as generated by
    :meth:`datetime.datetime.isoformat`), otherwise the conversion
    raises a :class:`FromJsonConversionError`
    """
    return FunctionBasedFromSimpleJsonConverter(datetime.fromisoformat, str, datetime)


# mimic class name
# noinspection PyPep8Naming
def FromDatetime() -> ToJsonConverter[datetime]:  # noqa: N802
    """Return a converter that converts objects of type :class:`datetime.datetime`.

    A ``datetime`` is converted to its iso-string using :meth:`datetime.datetime.isoformat`
    """
    return FunctionBasedToSimpleJsonConverter[datetime](datetime.isoformat, datetime)
