version: 1
policies:
  Token-Permissions:
      score: 10
      mode: enforced
  Dangerous-Workflow:
      score: 10
      mode: enforced
  License:
      score: 9
      mode: enforced
  Pinned-Dependencies:
      score: 10
      mode: enforced
  Security-Policy:
      score: 10
      mode: enforced
  SAST:
      score: 10
      mode: enforced
  Packaging:
      score: 10
      mode: enforced
  Binary-Artifacts:
      score: 10
      mode: enforced
  Signed-Releases:
      score: 10
      mode: disabled
  Dependency-Update-Tool:
      score: 10
      mode: enforced
  Vulnerabilities:
      score: 10
      mode: enforced
  CI-Tests:
      score: 10
      mode: enforced
  Maintained:
      score: 1
      mode: enforced
