version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --inexact --active

sphinx:
  configuration: docs/source/conf.py
